from pathlib import Path

EXPERIMENTS_FOLDER = Path("artifacts")
MODELS_FOLDER_NAME = Path("models")
CONFIG_FILE_NAME = Path("config.py")
DATASET_SCRIPTS_FOLDER = Path("datasets_scripts")

MODELS_FOLDER = EXPERIMENTS_FOLDER / MODELS_FOLDER_NAME
WEIGHTS_FILE = "model_weights"
DEFAULT_MASK_ID = -1
DEFAULT_INPUT_ONLY_MASK_ID = -2
